name: Build Project64

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: windows-2025

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        repository: project64/project64
        ref: 3.0-develop

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '15'

    - name: Build app for release
      run: msbuild Project64.sln

    - name: ls
      run: dir
