name: Build Project64

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: windows-2025

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive
        repository: ianwal/project64

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Build app for release
      run: msbuild Project64.sln

    - name: ls
      run: dir

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: Project64Build
        path: bin
